spring:
  profiles:
    active: kafka-template
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ShawarmaOrder:com.springstudy.shawarma_cloud.model.ShawarmaOrder
  application:
    name: shawarma-cloud
  datasource:
    generate-unique-name: false
    name: shawarmacloud
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
        security: DEBUG
shawarma:
  order:
    pageSize: 10