spring:
  application:
    name: shawarma-cloud
  datasource:
    generate-unique-name: false
    name: shawarmacloud
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
        security: DEBUG
