spring:
  cassandra:
    local-datacenter: datacenter1
    contact-points: localhost
    port: 9042
    keyspace-name: shawarmacloud
    schema-action: recreate
  application:
    name: shawarma-cloud
