server:
  port: 8082
spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: shawarmacloud_kitchen
      properties:
        spring:
          json:
            type:
              mapping=com: ShawarmaOrder:com.ergos.shawarmacloud_kitchen.model.ShawarmaOrder
            trusted.packages: "*"
#
#---
#spring:
#  artemis:
#    host: localhost
#    port: 61616
#    user: artemis
#    password: artemis
#    embedded:
#      enabled: false
#  jms:
#    template:
#      receive-timeout: 2


#---
#spring:
#  jms:
#    template:
#     receive-timeout: 3