spring:
  application:
    name: shawarma-cloud
  data:
    mongodb:
      host: localhost
      port: 27017
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug